package us.z1x.fidont.ui

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// tonal spot scheme of the icon's #7FE3C4
val LightColors =
    lightColorScheme(
        primary = Color(0xFF126B56),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFA3F2D7),
        onPrimaryContainer = Color(0xFF005140),
        inversePrimary = Color(0xFF87D6BC),
        secondary = Color(0xFF4B635A),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCEE9DD),
        onSecondaryContainer = Color(0xFF344C43),
        tertiary = Color(0xFF406376),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFC4E7FF),
        onTertiaryContainer = Color(0xFF284B5D),
        background = Color(0xFFF5FBF6),
        onBackground = Color(0xFF171D1A),
        surface = Color(0xFFF5FBF6),
        onSurface = Color(0xFF171D1A),
        surfaceVariant = Color(0xFFDBE5DF),
        onSurfaceVariant = Color(0xFF3F4945),
        surfaceTint = Color(0xFF126B56),
        inverseSurface = Color(0xFF2B322F),
        inverseOnSurface = Color(0xFFECF2EE),
        outline = Color(0xFF6F7975),
        outlineVariant = Color(0xFFBFC9C3),
        surfaceBright = Color(0xFFF5FBF6),
        surfaceContainer = Color(0xFFE9EFEB),
        surfaceContainerHigh = Color(0xFFE4EAE5),
        surfaceContainerHighest = Color(0xFFDEE4E0),
        surfaceContainerLow = Color(0xFFEFF5F1),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFD5DBD7),
        primaryFixed = Color(0xFFA3F2D7),
        primaryFixedDim = Color(0xFF87D6BC),
        onPrimaryFixed = Color(0xFF002018),
        onPrimaryFixedVariant = Color(0xFF005140),
        secondaryFixed = Color(0xFFCEE9DD),
        secondaryFixedDim = Color(0xFFB2CCC1),
        onSecondaryFixed = Color(0xFF072019),
        onSecondaryFixedVariant = Color(0xFF344C43),
        tertiaryFixed = Color(0xFFC4E7FF),
        tertiaryFixedDim = Color(0xFFA8CBE2),
        onTertiaryFixed = Color(0xFF001E2C),
        onTertiaryFixedVariant = Color(0xFF284B5D),
    )

val DarkColors =
    darkColorScheme(
        primary = Color(0xFF87D6BC),
        onPrimary = Color(0xFF00382B),
        primaryContainer = Color(0xFF005140),
        onPrimaryContainer = Color(0xFFA3F2D7),
        inversePrimary = Color(0xFF126B56),
        secondary = Color(0xFFB2CCC1),
        onSecondary = Color(0xFF1E352D),
        secondaryContainer = Color(0xFF344C43),
        onSecondaryContainer = Color(0xFFCEE9DD),
        tertiary = Color(0xFFA8CBE2),
        onTertiary = Color(0xFF0D3446),
        tertiaryContainer = Color(0xFF284B5D),
        onTertiaryContainer = Color(0xFFC4E7FF),
        background = Color(0xFF0F1512),
        onBackground = Color(0xFFDEE4E0),
        surface = Color(0xFF0F1512),
        onSurface = Color(0xFFDEE4E0),
        surfaceVariant = Color(0xFF3F4945),
        onSurfaceVariant = Color(0xFFBFC9C3),
        surfaceTint = Color(0xFF87D6BC),
        inverseSurface = Color(0xFFDEE4E0),
        inverseOnSurface = Color(0xFF2B322F),
        outline = Color(0xFF89938E),
        outlineVariant = Color(0xFF3F4945),
        surfaceBright = Color(0xFF343B38),
        surfaceContainer = Color(0xFF1B211E),
        surfaceContainerHigh = Color(0xFF252B29),
        surfaceContainerHighest = Color(0xFF303633),
        surfaceContainerLow = Color(0xFF171D1A),
        surfaceContainerLowest = Color(0xFF090F0D),
        surfaceDim = Color(0xFF0F1512),
        primaryFixed = Color(0xFFA3F2D7),
        primaryFixedDim = Color(0xFF87D6BC),
        onPrimaryFixed = Color(0xFF002018),
        onPrimaryFixedVariant = Color(0xFF005140),
        secondaryFixed = Color(0xFFCEE9DD),
        secondaryFixedDim = Color(0xFFB2CCC1),
        onSecondaryFixed = Color(0xFF072019),
        onSecondaryFixedVariant = Color(0xFF344C43),
        tertiaryFixed = Color(0xFFC4E7FF),
        tertiaryFixedDim = Color(0xFFA8CBE2),
        onTertiaryFixed = Color(0xFF001E2C),
        onTertiaryFixedVariant = Color(0xFF284B5D),
    )
